# Generated by cucumber-sinatra. (Thu Jul 15 12:27:57 -0400 2010)

require File.join(File.dirname(__FILE__), '..', '..', 'lib/spec_server.rb')

require 'capybara'
require 'capybara/cucumber'
require 'capybara/envjs'
require 'spec'

SpecServer.set(:environment, :test)

World do
  Capybara.app = SpecServer
  Capybara.javascript_driver = :envjs
  include Capybara
  include Spec::Expectations
  include Spec::Matchers
end
